name: Backend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker compose -f docker/compose.yml build

      - name: Deploy to Railway
        uses: railwayapp/railway-deploy@v1
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Clean Docker Containers
        run: |
          docker compose -f docker/compose.yml down

